# Generated by Django 6.0.7 on 2026-07-17 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='criterios_aceptacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='proposito',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Por Hacer', 'Por Hacer'), ('En Progreso', 'En Progreso'), ('En revisión', 'En revisión'), ('Terminado', 'Terminado')], default='Por Hacer', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
