# Generated by Django 6.0.7 on 2026-07-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
