# Generated by Django 6.0.7 on 2026-07-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tarea_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='es_finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
